# Generated by Django 5.2.8 on 2025-11-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('scholarship_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('scholarship_name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=100)),
                ('category_eligible', models.CharField(default='All', max_length=50)),
                ('income_limit', models.IntegerField(default=0, help_text='0 means no limit')),
                ('min_cutoff', models.FloatField(default=0)),
                ('min_percentage', models.FloatField(default=0)),
                ('gender', models.CharField(choices=[('All', 'All'), ('Male', 'Male Only'), ('Female', 'Female Only')], default='All', max_length=10)),
                ('amount_per_year', models.IntegerField()),
                ('duration_years', models.IntegerField(default=4)),
                ('total_value', models.IntegerField(default=0)),
                ('amount_category', models.CharField(choices=[('Basic', 'Basic (< ₹15,000)'), ('Standard', 'Standard (₹15,000 - ₹30,000)'), ('Premium', 'Premium (₹30,000 - ₹50,000)'), ('Elite', 'Elite (> ₹50,000)')], default='Standard', max_length=20)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('documents_required', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('accessibility_score', models.FloatField(default=50)),
                ('provider_reliability', models.FloatField(default=70)),
                ('attractiveness_score', models.FloatField(default=50)),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ['-amount_per_year'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('applied', 'Applied'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='interested', max_length=20)),
                ('eligibility_status', models.CharField(default='unknown', max_length=20)),
                ('match_score', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'scholarship')},
            },
        ),
    ]
