# Generated by Django 5.2.8 on 2025-11-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('popularity_score', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-popularity_score'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('college_name', models.CharField(max_length=200)),
                ('college_type', models.CharField(choices=[('Government', 'Government'), ('Private Aided', 'Private Aided'), ('Private', 'Private')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('accreditation', models.CharField(choices=[('NAAC A++', 'NAAC A++'), ('NAAC A+', 'NAAC A+'), ('NAAC A', 'NAAC A'), ('NAAC B++', 'NAAC B++'), ('NAAC B+', 'NAAC B+'), ('NAAC B', 'NAAC B'), ('None', 'Not Accredited')], default='None', max_length=20)),
                ('ranking', models.IntegerField(default=100)),
                ('total_seats', models.IntegerField(default=0)),
                ('hostel_available', models.BooleanField(default=False)),
                ('placement_rate', models.FloatField(default=0)),
                ('avg_package_lpa', models.FloatField(default=0)),
                ('website', models.URLField(blank=True)),
                ('quality_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_score', models.FloatField()),
                ('category', models.CharField(max_length=5)),
                ('preferred_branches', models.CharField(max_length=200)),
                ('preferred_districts', models.CharField(max_length=200)),
                ('total_recommendations', models.IntegerField()),
                ('top_college', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation History',
                'verbose_name_plural': 'Recommendation Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollegeBranchCutoff',
            fields=[
                ('cutoff_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('OC', 'OC'), ('BC', 'BC'), ('BCM', 'BCM'), ('MBC', 'MBC'), ('DNC', 'DNC'), ('SC', 'SC'), ('SCA', 'SCA'), ('ST', 'ST')], max_length=5)),
                ('cutoff_2023', models.FloatField(default=0)),
                ('cutoff_2022', models.FloatField(default=0)),
                ('cutoff_2021', models.FloatField(default=0)),
                ('seats_available', models.IntegerField(default=0)),
                ('min_cutoff', models.FloatField(default=0)),
                ('max_cutoff', models.FloatField(default=200)),
                ('avg_cutoff', models.FloatField(default=0)),
                ('cutoff_trend', models.FloatField(default=0)),
                ('competition_intensity', models.FloatField(default=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='recommendations.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='recommendations.college')),
            ],
            options={
                'verbose_name': 'Cutoff',
                'verbose_name_plural': 'Cutoffs',
                'ordering': ['-cutoff_2023'],
                'unique_together': {('college', 'branch', 'category')},
            },
        ),
        migrations.CreateModel(
            name='SavedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=5)),
                ('rank', models.IntegerField()),
                ('total_score', models.FloatField()),
                ('cutoff', models.FloatField()),
                ('margin', models.FloatField()),
                ('admission_probability', models.CharField(max_length=50)),
                ('score_cutoff', models.FloatField(default=0)),
                ('score_branch', models.FloatField(default=0)),
                ('score_quality', models.FloatField(default=0)),
                ('score_placement', models.FloatField(default=0)),
                ('score_location', models.FloatField(default=0)),
                ('score_cost', models.FloatField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Recommendation',
                'verbose_name_plural': 'Saved Recommendations',
                'ordering': ['rank'],
                'unique_together': {('user', 'college', 'branch', 'category')},
            },
        ),
    ]
